[package]
name = "eris-accounting"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.71"
chrono = { version = "0" }
tokio = "1.29.1"

eris-db = { path = "../eris-db" }
eris-data = { path = "../eris-data" }
eris-banking = { path = "../eris-banking" }
